jobs:
  ci:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Install NDK
      run: 'SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager

        echo "y" | $SDKMANAGER "ndk;23.1.7779620" --sdk_root=${ANDROID_SDK_ROOT}

        '
    - continue-on-error: true
      name: Run release build
      run: ./gradlew assembleRelease
    - continue-on-error: true
      name: Run debug build
      run: ./gradlew assembleDebug
    - continue-on-error: true
      name: Upload artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: RedReader-debug.apk
        path: build/outputs/apk/debug/RedReader-debug.apk
    - continue-on-error: true
      name: Run PMD
      run: ./gradlew pmd
    - continue-on-error: true
      name: Run checkstyle
      run: ./gradlew checkstyle --stacktrace --info
    - continue-on-error: true
      name: Android Lint
      run: ./gradlew lint
    - continue-on-error: true
      name: Unit tests
      run: ./gradlew test
name: CI
on:
  repository_dispatch:
    types: trigger-ga___build.yml
